name: Invidious
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  invidious-helm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out invidious repo
        uses: actions/checkout@master
        with:
          repository: iv-org/invidious
      - name: Get dependencies
        run: |
          cd kubernetes
          helm repo add bitnami https://charts.bitnami.com/bitnami/
          helm dep build
          kubectl create configmap invidious-postgresql-init \
            --from-file=../config/sql/channels.sql \
            --from-file=../config/sql/videos.sql \
            --from-file=../config/sql/channel_videos.sql \
            --from-file=../config/sql/users.sql \
            --from-file=../config/sql/session_ids.sql \
            --from-file=../config/sql/nonces.sql \
            --from-file=../config/sql/annotations.sql \
            --from-file=../config/sql/playlists.sql \
            --from-file=../config/sql/playlist_videos.sql --dry-run=client -o yaml > templates/invidious-postgresql-init-cm.yaml

      - name: push chart to registry
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/gabisonfire
          username: gabisonfire
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: kubernetes