name: Invidious
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  invidious-helm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out invidious repo
        uses: actions/checkout@master
        with:
          repository: iv-org/invidious
      - name: Get dependencies
        run: |
          cd kubernetes
          helm repo add bitnami https://charts.bitnami.com/bitnami/
          helm dep build
      - name: push chart to registry
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/gabisonfire
          username: gabisonfire
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: kubernetes