name: Invidious
on: workflow_dispatch
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out invidious repo
        uses: actions/checkout@master
        with:
          repository: iv-org/invidious
      - name: Get dependencies
        run: |
          cd kubernetes
          helm dep build
      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4.1.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/Gabisonfire/charts
          username: gabisonfire
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: kubernetes